//! `POST /v1/chat/completions` — OpenAI-shaped entry point.
//!
//! Runs the auction, signs a [`DispatchToken`] naming the winning
//! primary node, then dispatches the actual inference job to that
//! node over libp2p (`Mesh::dispatch_inference`) and waits for the
//! reply — returning the final `content` directly in this response.
//!
//! This rides the node's *existing outbound* connection (it dialed the
//! coordinator to join the mesh), which is what makes it work for
//! nodes behind NAT — the common case for home/laptop GPU operators.
//! An earlier version of this handler returned `{ node_url,
//! dispatch_token }` and expected the caller to dial the node's HTTP
//! server directly; that only works for nodes with a public IP, which
//! most real operators don't have. The tradeoff: prompt and response
//! content now pass through the coordinator's enclave on their way to
//! and from the node (see `docs/architecture.md` for the full
//! discussion of why this is still the better choice than adding a
//! second, unattested relay component just to avoid it).
//!
//! ## Encrypted mode
//!
//! Clients that want prompt privacy (so neither the operator nor anyone
//! observing the TLS session to the coordinator can read their prompt)
//! can encrypt the `messages` array before posting:
//!
//! 1. `GET /enclave_health` → extract `x25519_pubkey_hex`
//! 2. Generate an ephemeral X25519 keypair client-side
//! 3. `shared = ECDH(client_ephemeral_priv, enclave_x25519_pub)`
//! 4. `aes_key = SHA-256("pinaivu-aes-key-v1" ‖ shared)`
//! 5. `(ciphertext, nonce) = AES-256-GCM(aes_key, JSON(messages))`
//! 6. Post with `client_x25519_pubkey_hex`, `messages_encrypted` (base64),
//!    `messages_nonce` (base64); omit `messages`.
//!
//! The coordinator decrypts inside the Nitro Enclave — the operator
//! never sees the plaintext prompt.

use std::time::{SystemTime, UNIX_EPOCH};

use aes_gcm::{
    Aes256Gcm, Key, Nonce,
    aead::{Aead, KeyInit},
};
use axum::{extract::State, Json};
use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use x25519_dalek::PublicKey as X25519PublicKey;

use crate::app::{AppError, AppState};
use crate::marketplace::auction::{
    collect_bids, fetch_warmth_map, pick_winner_with_warmth, DEFAULT_AUCTION_WINDOW,
};
use crate::mesh::{InferenceDispatch, InferenceReply};
use crate::protocol::{
    ClientSessionIntent, DispatchToken, InferenceRequest, NanoX, PrivacyLevel,
};
use nautilus_enclave::EnclaveKeyPair;

const DISPATCH_DEADLINE_MS: u64 = 60_000;
const DEFAULT_SETTLEMENT_ID: &str = "free";

#[derive(Debug, Clone, Deserialize)]
pub struct ChatMessage {
    pub role: String,
    pub content: String,
}

#[derive(Debug, Deserialize)]
pub struct ChatCompletionRequest {
    pub model: String,
    /// Plaintext messages. Omit when using encrypted mode.
    #[serde(default)]
    pub messages: Vec<ChatMessage>,
    /// Hex-encoded Ed25519 public key of the client, bound into the
    /// dispatch token so only this client can later authenticate to
    /// the chosen node.
    pub client_pubkey_hex: String,
    pub max_price_nanox: Option<u64>,
    #[serde(default)]
    pub privacy: Option<String>,
    /// Existing session to continue. If absent, the coordinator mints
    /// a fresh `session_id` and the node treats this as a cold start.
    #[serde(default)]
    pub session_id: Option<Uuid>,

    // ── Encrypted-mode fields (all three must be present together) ───────────
    /// Hex-encoded ephemeral X25519 public key generated by the client.
    /// Required for encrypted mode; absent in plaintext mode.
    pub client_x25519_pubkey_hex: Option<String>,
    /// Base64-encoded AES-256-GCM ciphertext of `JSON(messages)`.
    pub messages_encrypted: Option<String>,
    /// Base64-encoded 12-byte AES-256-GCM nonce.
    pub messages_nonce: Option<String>,

    /// AES-256 key (base64) for the node's Walrus session blob. Caller
    /// generates on first turn and persists locally; we mint a fresh
    /// one if absent. Forwarded to the node, never stored here.
    #[serde(default)]
    pub session_key: Option<String>,
    /// Cross-session memory facts recalled by a caller's own long-term
    /// memory store (e.g. chat-relayer's pgvector + Walrus stack).
    /// Forwarded into the node's assembled system prompt as-is.
    #[serde(default)]
    pub memwal_context: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct ChatCompletionResult {
    pub request_id: Uuid,
    pub session_id: Uuid,
    pub content: String,
    pub session_key: String,
    pub input_tokens: u32,
    pub output_tokens: u32,
    pub latency_ms: u32,
}

pub async fn chat_completions(
    State(state): State<AppState>,
    Json(req): Json<ChatCompletionRequest>,
) -> Result<Json<ChatCompletionResult>, AppError> {
    let request_id = Uuid::new_v4();
    let (session_id, session_intent) = match req.session_id {
        Some(id) => (id, ClientSessionIntent::Continue),
        None => (Uuid::new_v4(), ClientSessionIntent::New),
    };

    // Resolve messages — either decrypt the encrypted payload or use plaintext.
    let messages = decrypt_messages_if_encrypted(&state, &req)?;
    let new_user_message = messages
        .iter()
        .rev()
        .find(|m| m.role == "user")
        .map(|m| m.content.clone())
        .ok_or_else(|| AppError::BadRequest("messages must include a user turn".into()))?;

    let inference_request = InferenceRequest {
        request_id,
        session_id,
        model: req.model.clone(),
        privacy: parse_privacy(req.privacy.as_deref()),
        session_intent,
    };

    let rx = state
        .mesh()
        .publish_request(&inference_request)
        .await
        .map_err(|e| {
            let msg = e.to_string();
            if msg.contains("NoPeersSubscribed") || msg.contains("InsufficientPeers") {
                AppError::NoNodes("no GPU nodes subscribed to this model topic".into())
            } else {
                AppError::Internal(format!("mesh publish: {e}"))
            }
        })?;

    let bids = collect_bids(rx, DEFAULT_AUCTION_WINDOW).await;
    // Warmth lookup: which nodes already have this session's KV/blob
    // cached locally? Empty for new sessions and stateless deployments;
    // the auction stays competitive on price + latency + reputation.
    let pool = state.pg_pool().await;
    let warmth = fetch_warmth_map(pool.as_ref(), session_id).await;
    let winner = pick_winner_with_warmth(&bids, &warmth)
        .ok_or_else(|| AppError::NoNodes("auction closed with no bids".into()))?;

    // Record peer_id → Sui payout address for every bidder so the
    // completion handler can build payment rows without a DB round-trip.
    let payout_addresses: std::collections::HashMap<String, String> = bids
        .iter()
        .filter(|b| !b.payout_address.is_empty())
        .map(|b| (b.node_peer_id.0.clone(), b.payout_address.clone()))
        .collect();
    state
        .mesh()
        .set_payout_addresses(request_id, payout_addresses)
        .await;

    let client_pubkey = decode_hex_pubkey(&req.client_pubkey_hex)?;
    let now_ms = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);

    let max_price = NanoX(req.max_price_nanox.unwrap_or(u64::MAX));

    let token = DispatchToken {
        request_id,
        session_id,
        client_pubkey,
        primary_peer_id: winner.node_peer_id.clone(),
        settlement_id: DEFAULT_SETTLEMENT_ID.to_string(),
        max_price_nanox: max_price,
        issued_at_ms: now_ms,
        deadline_ms: now_ms + DISPATCH_DEADLINE_MS,
        coordinator_pubkey: [0u8; 32],
        node_x25519_pubkey: winner.node_x25519_pubkey,
        signature: Vec::new(),
    }
    .sign(state.enclave_key().signing_key());

    let session_key = req.session_key.clone().unwrap_or_else(|| {
        use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
        use rand::RngCore;
        let mut k = [0u8; 32];
        rand::thread_rng().fill_bytes(&mut k);
        B64.encode(k)
    });

    let peer_id: libp2p::PeerId = winner.node_peer_id.0.parse().map_err(|e| {
        AppError::Internal(format!("winning bid has invalid peer_id: {e}"))
    })?;

    let dispatch = InferenceDispatch {
        dispatch_token: token,
        session_key: session_key.clone(),
        new_user_message,
        memwal_context: req.memwal_context.clone(),
    };

    let reply: InferenceReply = state
        .mesh()
        .dispatch_inference(peer_id, dispatch)
        .await
        .map_err(|e| AppError::Upstream(format!("node dispatch failed: {e}")))?;

    if let Some(err) = reply.error {
        return Err(AppError::Upstream(format!("node returned an error: {err}")));
    }

    Ok(Json(ChatCompletionResult {
        request_id,
        session_id,
        content: reply.content,
        session_key,
        input_tokens: reply.input_tokens,
        output_tokens: reply.output_tokens,
        latency_ms: reply.latency_ms,
    }))
}

/// Resolve the messages for this request.
///
/// If all three encrypted-mode fields are present, performs ECDH inside
/// the enclave and decrypts the messages JSON. Otherwise returns the
/// plaintext `messages` field as-is. Returns `BadRequest` if any
/// encrypted-mode field is malformed or decryption fails.
fn decrypt_messages_if_encrypted(
    state: &AppState,
    req: &ChatCompletionRequest,
) -> Result<Vec<ChatMessage>, AppError> {
    match (
        req.client_x25519_pubkey_hex.as_deref(),
        req.messages_encrypted.as_deref(),
        req.messages_nonce.as_deref(),
    ) {
        (Some(x25519_hex), Some(enc_b64), Some(nonce_b64)) => {
            // Decode the client's ephemeral X25519 public key.
            let client_pub_bytes = hex::decode(x25519_hex).map_err(|_| {
                AppError::BadRequest("client_x25519_pubkey_hex must be valid hex".into())
            })?;
            let client_pub_arr: [u8; 32] = client_pub_bytes.try_into().map_err(|_| {
                AppError::BadRequest("client_x25519_pubkey_hex must be exactly 32 bytes".into())
            })?;
            let client_pub = X25519PublicKey::from(client_pub_arr);

            // ECDH inside the enclave → AES-256-GCM key.
            let shared_secret = state.enclave_key().ecdh(&client_pub);
            let aes_key_bytes = EnclaveKeyPair::derive_aes_key(&shared_secret);

            // Decode the base64 ciphertext and nonce.
            let ciphertext = BASE64.decode(enc_b64).map_err(|_| {
                AppError::BadRequest("messages_encrypted must be valid base64".into())
            })?;
            let nonce_bytes = BASE64.decode(nonce_b64).map_err(|_| {
                AppError::BadRequest("messages_nonce must be valid base64".into())
            })?;
            if nonce_bytes.len() != 12 {
                return Err(AppError::BadRequest(
                    "messages_nonce must decode to exactly 12 bytes".into(),
                ));
            }

            // AES-256-GCM decrypt.
            let key    = Key::<Aes256Gcm>::from_slice(&aes_key_bytes);
            let cipher = Aes256Gcm::new(key);
            let nonce  = Nonce::from_slice(&nonce_bytes);
            let plaintext = cipher
                .decrypt(nonce, ciphertext.as_ref())
                .map_err(|_| AppError::BadRequest("prompt decryption failed".into()))?;

            // Parse the decrypted JSON as a messages array.
            serde_json::from_slice::<Vec<ChatMessage>>(&plaintext).map_err(|_| {
                AppError::BadRequest(
                    "decrypted payload is not a valid JSON messages array".into(),
                )
            })
        }
        (None, None, None) => {
            // Plaintext mode — use messages as-is.
            Ok(req.messages.clone())
        }
        _ => Err(AppError::BadRequest(
            "encrypted mode requires all three fields: \
             client_x25519_pubkey_hex, messages_encrypted, messages_nonce"
                .into(),
        )),
    }
}

fn parse_privacy(s: Option<&str>) -> PrivacyLevel {
    match s.unwrap_or("standard").to_ascii_lowercase().as_str() {
        "private" => PrivacyLevel::Private,
        "fragmented" => PrivacyLevel::Fragmented,
        "maximum" => PrivacyLevel::Maximum,
        _ => PrivacyLevel::Standard,
    }
}

fn decode_hex_pubkey(s: &str) -> Result<[u8; 32], AppError> {
    let raw = hex::decode(s).map_err(|_| AppError::BadRequest("client_pubkey_hex must be hex".into()))?;
    raw.as_slice()
        .try_into()
        .map_err(|_| AppError::BadRequest("client_pubkey_hex must be 32 bytes".into()))
}
