//! `POST /v1/chat/completions` — OpenAI-shaped entry point.
//!
//! Runs the auction on behalf of the client, signs a [`DispatchToken`]
//! naming the winning primary node, and returns
//! `{ request_id, node_url, dispatch_token }`. The client then opens
//! its own HTTPS connection to `node_url` to receive the streamed
//! response — the coordinator is never in the response data path.
//!
//! ## Encrypted mode
//!
//! Clients that want prompt privacy (so neither the operator nor anyone
//! observing the TLS session to the coordinator can read their prompt)
//! can encrypt the `messages` array before posting:
//!
//! 1. `GET /enclave_health` → extract `x25519_pubkey_hex`
//! 2. Generate an ephemeral X25519 keypair client-side
//! 3. `shared = ECDH(client_ephemeral_priv, enclave_x25519_pub)`
//! 4. `aes_key = SHA-256("pinaivu-aes-key-v1" ‖ shared)`
//! 5. `(ciphertext, nonce) = AES-256-GCM(aes_key, JSON(messages))`
//! 6. Post with `client_x25519_pubkey_hex`, `messages_encrypted` (base64),
//!    `messages_nonce` (base64); omit `messages`.
//!
//! The coordinator decrypts inside the Nitro Enclave — the operator
//! never sees the plaintext prompt.
//!
//! In a future slice this handler will return a `307` redirect to the
//! primary node's URL with `X-Pinaivu-Dispatch-Token` in the header so
//! the standard OpenAI SDK works transparently. For now we return a
//! JSON body, which keeps the integration test simple.

use std::time::{SystemTime, UNIX_EPOCH};

use aes_gcm::{
    Aes256Gcm, Key, Nonce,
    aead::{Aead, KeyInit},
};
use axum::{extract::State, Extension, Json};
use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use x25519_dalek::PublicKey as X25519PublicKey;

use crate::api::usage;
use crate::app::{AppError, AppState};
use crate::auth::key::ApiKeyContext;
use crate::marketplace::auction::{collect_bids, pick_winner, DEFAULT_AUCTION_WINDOW};
use crate::protocol::{DispatchToken, InferenceRequest, NanoX, PrivacyLevel};
use nautilus_enclave::EnclaveKeyPair;

const DISPATCH_DEADLINE_MS: u64 = 60_000;
const DEFAULT_SETTLEMENT_ID: &str = "free";

#[derive(Debug, Clone, Deserialize)]
pub struct ChatMessage {
    pub role: String,
    pub content: String,
}

#[derive(Debug, Deserialize)]
pub struct ChatCompletionRequest {
    pub model: String,
    /// Plaintext messages. Omit when using encrypted mode.
    #[serde(default)]
    pub messages: Vec<ChatMessage>,
    /// Hex-encoded Ed25519 public key of the client, bound into the
    /// dispatch token so only this client can later authenticate to
    /// the chosen node.
    pub client_pubkey_hex: String,
    pub max_price_nanox: Option<u64>,
    #[serde(default)]
    pub privacy: Option<String>,

    // ── Encrypted-mode fields (all three must be present together) ───────────
    /// Hex-encoded ephemeral X25519 public key generated by the client.
    /// Required for encrypted mode; absent in plaintext mode.
    pub client_x25519_pubkey_hex: Option<String>,
    /// Base64-encoded AES-256-GCM ciphertext of `JSON(messages)`.
    pub messages_encrypted: Option<String>,
    /// Base64-encoded 12-byte AES-256-GCM nonce.
    pub messages_nonce: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct ChatCompletionDispatch {
    pub request_id: Uuid,
    pub node_url: String,
    pub dispatch_token: DispatchToken,
}

pub async fn chat_completions(
    State(state): State<AppState>,
    // Optional: present when called through require_api_key middleware,
    // absent in tests that use build_router_no_auth.
    key_ctx: Option<Extension<ApiKeyContext>>,
    Json(req): Json<ChatCompletionRequest>,
) -> Result<Json<ChatCompletionDispatch>, AppError> {
    let request_id = Uuid::new_v4();
    let session_id = Uuid::new_v4();

    // Resolve messages — either decrypt the encrypted payload or use plaintext.
    let _messages = decrypt_messages_if_encrypted(&state, &req)?;

    let inference_request = InferenceRequest {
        request_id,
        session_id,
        model: req.model.clone(),
        privacy: parse_privacy(req.privacy.as_deref()),
    };

    let rx = state
        .mesh()
        .publish_request(&inference_request)
        .await
        .map_err(|e| {
            let msg = e.to_string();
            if msg.contains("NoPeersSubscribed") || msg.contains("InsufficientPeers") {
                AppError::NoNodes("no GPU nodes subscribed to this model topic".into())
            } else {
                AppError::Internal(format!("mesh publish: {e}"))
            }
        })?;

    let bids = collect_bids(rx, DEFAULT_AUCTION_WINDOW).await;
    let winner = pick_winner(&bids)
        .ok_or_else(|| AppError::NoNodes("auction closed with no bids".into()))?;

    // Record peer_id → Sui payout address for every bidder so the
    // completion handler can build payment rows without a DB round-trip.
    let payout_addresses: std::collections::HashMap<String, String> = bids
        .iter()
        .filter(|b| !b.payout_address.is_empty())
        .map(|b| (b.node_peer_id.0.clone(), b.payout_address.clone()))
        .collect();
    state
        .mesh()
        .set_payout_addresses(request_id, payout_addresses)
        .await;

    let client_pubkey = decode_hex_pubkey(&req.client_pubkey_hex)?;
    let now_ms = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);

    let max_price = NanoX(req.max_price_nanox.unwrap_or(u64::MAX));

    let token = DispatchToken {
        request_id,
        client_pubkey,
        primary_peer_id: winner.node_peer_id.clone(),
        settlement_id: DEFAULT_SETTLEMENT_ID.to_string(),
        max_price_nanox: max_price,
        issued_at_ms: now_ms,
        deadline_ms: now_ms + DISPATCH_DEADLINE_MS,
        coordinator_pubkey: [0u8; 32],
        node_x25519_pubkey: winner.node_x25519_pubkey,
        signature: Vec::new(),
    }
    .sign(state.enclave_key().signing_key());

    // Record usage for billing. Fire-and-forget — a DB hiccup must not
    // block the client. Token counts are 0 now; updated on CompletionAck.
    if let (Some(Extension(ctx)), Some(pool)) = (key_ctx, state.pg_pool().await) {
        let key_id = ctx.api_key_id;
        let model  = req.model.clone();
        tokio::spawn(async move {
            usage::record_dispatch(&pool, request_id, key_id, &model).await;
        });
    }

    // Bids carry the winning node's HTTP endpoint directly — the node
    // advertises its own URL so the coordinator doesn't have to guess.
    let node_url = winner.http_endpoint.clone();

    Ok(Json(ChatCompletionDispatch {
        request_id,
        node_url,
        dispatch_token: token,
    }))
}

/// Resolve the messages for this request.
///
/// If all three encrypted-mode fields are present, performs ECDH inside
/// the enclave and decrypts the messages JSON. Otherwise returns the
/// plaintext `messages` field as-is. Returns `BadRequest` if any
/// encrypted-mode field is malformed or decryption fails.
fn decrypt_messages_if_encrypted(
    state: &AppState,
    req: &ChatCompletionRequest,
) -> Result<Vec<ChatMessage>, AppError> {
    match (
        req.client_x25519_pubkey_hex.as_deref(),
        req.messages_encrypted.as_deref(),
        req.messages_nonce.as_deref(),
    ) {
        (Some(x25519_hex), Some(enc_b64), Some(nonce_b64)) => {
            // Decode the client's ephemeral X25519 public key.
            let client_pub_bytes = hex::decode(x25519_hex).map_err(|_| {
                AppError::BadRequest("client_x25519_pubkey_hex must be valid hex".into())
            })?;
            let client_pub_arr: [u8; 32] = client_pub_bytes.try_into().map_err(|_| {
                AppError::BadRequest("client_x25519_pubkey_hex must be exactly 32 bytes".into())
            })?;
            let client_pub = X25519PublicKey::from(client_pub_arr);

            // ECDH inside the enclave → AES-256-GCM key.
            let shared_secret = state.enclave_key().ecdh(&client_pub);
            let aes_key_bytes = EnclaveKeyPair::derive_aes_key(&shared_secret);

            // Decode the base64 ciphertext and nonce.
            let ciphertext = BASE64.decode(enc_b64).map_err(|_| {
                AppError::BadRequest("messages_encrypted must be valid base64".into())
            })?;
            let nonce_bytes = BASE64.decode(nonce_b64).map_err(|_| {
                AppError::BadRequest("messages_nonce must be valid base64".into())
            })?;
            if nonce_bytes.len() != 12 {
                return Err(AppError::BadRequest(
                    "messages_nonce must decode to exactly 12 bytes".into(),
                ));
            }

            // AES-256-GCM decrypt.
            let key    = Key::<Aes256Gcm>::from_slice(&aes_key_bytes);
            let cipher = Aes256Gcm::new(key);
            let nonce  = Nonce::from_slice(&nonce_bytes);
            let plaintext = cipher
                .decrypt(nonce, ciphertext.as_ref())
                .map_err(|_| AppError::BadRequest("prompt decryption failed".into()))?;

            // Parse the decrypted JSON as a messages array.
            serde_json::from_slice::<Vec<ChatMessage>>(&plaintext).map_err(|_| {
                AppError::BadRequest(
                    "decrypted payload is not a valid JSON messages array".into(),
                )
            })
        }
        (None, None, None) => {
            // Plaintext mode — use messages as-is.
            Ok(req.messages.clone())
        }
        _ => Err(AppError::BadRequest(
            "encrypted mode requires all three fields: \
             client_x25519_pubkey_hex, messages_encrypted, messages_nonce"
                .into(),
        )),
    }
}

fn parse_privacy(s: Option<&str>) -> PrivacyLevel {
    match s.unwrap_or("standard").to_ascii_lowercase().as_str() {
        "private" => PrivacyLevel::Private,
        "fragmented" => PrivacyLevel::Fragmented,
        "maximum" => PrivacyLevel::Maximum,
        _ => PrivacyLevel::Standard,
    }
}

fn decode_hex_pubkey(s: &str) -> Result<[u8; 32], AppError> {
    let raw = hex::decode(s).map_err(|_| AppError::BadRequest("client_pubkey_hex must be hex".into()))?;
    raw.as_slice()
        .try_into()
        .map_err(|_| AppError::BadRequest("client_pubkey_hex must be 32 bytes".into()))
}
