/**
 * Pinaivu coordinator Sui sidecar.
 *
 * Long-lived Express server colocated with the Rust coordinator inside
 * the Nitro Enclave. The coordinator never holds the operator private
 * key in its own address space — it asks this sidecar to sign + submit
 * Sui transactions on its behalf.
 *
 * Endpoints (v1):
 *   GET  /health                → liveness
 *   POST /sui/register-enclave  → submit pinaivu::enclave::register_enclave
 *
 * Settlement endpoints (vault::settle batching) land alongside the
 * payment-ledger work.
 *
 * Auth: every request must carry `X-Sidecar-Secret: <SIDECAR_SECRET>`
 * matching the env value (timing-safe-compared). The secret is
 * generated by the enclave init process at boot and passed to both
 * the Rust coordinator and this sidecar via env.
 */

import express, { Request, Response, NextFunction } from "express";
import { timingSafeEqual } from "crypto";
import { SuiJsonRpcClient, getJsonRpcFullnodeUrl } from "@mysten/sui/jsonRpc";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { decodeSuiPrivateKey } from "@mysten/sui/cryptography";
import { Transaction } from "@mysten/sui/transactions";
import { z } from "zod";

const PORT = Number(process.env.SIDECAR_PORT || 8200);
const NETWORK = (process.env.SUI_NETWORK || "mainnet") as
    | "mainnet"
    | "testnet"
    | "devnet";
const SUI_RPC_URL = process.env.SUI_RPC_URL || getJsonRpcFullnodeUrl(NETWORK);

const OPERATOR_PRIVATE_KEY = (process.env.OPERATOR_PRIVATE_KEY || "").trim();
const PINAIVU_PACKAGE_ID = (process.env.PINAIVU_PACKAGE_ID || "").trim();
const PINAIVU_ENCLAVE_CONFIG_ID = (process.env.PINAIVU_ENCLAVE_CONFIG_ID || "").trim();
const PINAIVU_CAP_ID = (process.env.PINAIVU_CAP_ID || "").trim();
const SIDECAR_SECRET = (process.env.SIDECAR_SECRET || "").trim();

if (!OPERATOR_PRIVATE_KEY) {
    console.error("[sidecar] FATAL: OPERATOR_PRIVATE_KEY env not set");
    process.exit(1);
}
if (!SIDECAR_SECRET) {
    console.error("[sidecar] FATAL: SIDECAR_SECRET env not set");
    process.exit(1);
}
if (!PINAIVU_PACKAGE_ID || !PINAIVU_ENCLAVE_CONFIG_ID || !PINAIVU_CAP_ID) {
    console.warn(
        "[sidecar] WARNING: PINAIVU_PACKAGE_ID / _ENCLAVE_CONFIG_ID / _CAP_ID not set — /sui/register-enclave will fail",
    );
}

// Decode the operator key once at boot.
const { secretKey } = decodeSuiPrivateKey(OPERATOR_PRIVATE_KEY);
const operatorKeypair = Ed25519Keypair.fromSecretKey(secretKey);
const operatorAddress = operatorKeypair.toSuiAddress();
console.log(`[sidecar] operator address: ${operatorAddress}`);

const suiClient = new SuiJsonRpcClient({ url: SUI_RPC_URL, network: NETWORK });

const app = express();
app.use(express.json({ limit: "1mb" }));

// ── auth middleware ──────────────────────────────────────────────────────
app.use((req: Request, res: Response, next: NextFunction) => {
    if (req.path === "/health") return next();
    const supplied = (req.header("x-sidecar-secret") || "").trim();
    if (supplied.length === 0) {
        return res.status(401).json({ error: "missing X-Sidecar-Secret" });
    }
    const a = Buffer.from(supplied);
    const b = Buffer.from(SIDECAR_SECRET);
    if (a.length !== b.length || !timingSafeEqual(a, b)) {
        return res.status(401).json({ error: "bad X-Sidecar-Secret" });
    }
    next();
});

// ── /health ──────────────────────────────────────────────────────────────
app.get("/health", (_req: Request, res: Response) => {
    res.json({
        status: "ok",
        operator: operatorAddress,
        network: NETWORK,
    });
});

// ── /sui/register-enclave ────────────────────────────────────────────────
const RegisterEnclaveReq = z.object({
    /** Raw COSE_Sign1 attestation document bytes, base64-encoded. */
    attestation_b64: z.string().min(1),
});

app.post("/sui/register-enclave", async (req: Request, res: Response) => {
    const parsed = RegisterEnclaveReq.safeParse(req.body);
    if (!parsed.success) {
        return res.status(400).json({ error: parsed.error.message });
    }

    if (!PINAIVU_PACKAGE_ID || !PINAIVU_ENCLAVE_CONFIG_ID || !PINAIVU_CAP_ID) {
        return res.status(500).json({
            error: "package / config / cap ids not configured",
        });
    }

    try {
        const attBytes = Buffer.from(parsed.data.attestation_b64, "base64");

        // Build PTB:
        //   doc = sui::nitro_attestation::load_nitro_attestation(att_bytes, clock)
        //   pinaivu::enclave::register_enclave<ENCLAVE>(config, cap, doc)
        const tx = new Transaction();
        const doc = tx.moveCall({
            target: "0x2::nitro_attestation::load_nitro_attestation",
            arguments: [tx.pure.vector("u8", Array.from(attBytes)), tx.object.clock()],
        });
        tx.moveCall({
            target: `${PINAIVU_PACKAGE_ID}::enclave::register_enclave`,
            typeArguments: [`${PINAIVU_PACKAGE_ID}::enclave::ENCLAVE`],
            arguments: [
                tx.object(PINAIVU_ENCLAVE_CONFIG_ID),
                tx.object(PINAIVU_CAP_ID),
                doc,
            ],
        });

        const result = await suiClient.signAndExecuteTransaction({
            signer: operatorKeypair,
            transaction: tx,
            options: { showObjectChanges: true, showEffects: true },
        });

        if (result.effects?.status?.status !== "success") {
            return res.status(500).json({
                error: "register_enclave on-chain failed",
                effects: result.effects,
            });
        }

        // Find the newly-created Enclave<ENCLAVE> shared object.
        const enclaveType = `${PINAIVU_PACKAGE_ID}::enclave::Enclave<${PINAIVU_PACKAGE_ID}::enclave::ENCLAVE>`;
        const created = (result.objectChanges || []).find(
            (c) => c.type === "created" && (c as any).objectType === enclaveType,
        );
        const enclaveObjectId = created ? (created as any).objectId : null;

        return res.json({
            tx_digest: result.digest,
            enclave_object_id: enclaveObjectId,
        });
    } catch (err: any) {
        console.error("[sidecar] register-enclave error:", err);
        return res.status(500).json({ error: err.message ?? String(err) });
    }
});

// ── /sui/settle ─────────────────────────────────────────────────────────────
// Build and submit a vault::settle PTB for one (request_id, payee, amount).
// The receipt_b64 field is the BCS+base64 encoded signed RoutingReceipt
// already produced by the coordinator; the sidecar passes it straight
// through to the on-chain verify_completion_receipt call.
const SettleSchema = z.object({
    request_id: z.string(),
    payee_sui_address: z.string(),
    amount_nanox: z.number().int().positive(),
    receipt_b64: z.string(),
});

const PINAIVU_VAULT_ID = (process.env.PINAIVU_VAULT_ID || "").trim();

app.post("/sui/settle", async (req: Request, res: Response) => {
    const parsed = SettleSchema.safeParse(req.body);
    if (!parsed.success) {
        return res.status(400).json({ error: "invalid request", details: parsed.error.issues });
    }
    if (!PINAIVU_PACKAGE_ID || !PINAIVU_VAULT_ID) {
        return res.status(503).json({ error: "PINAIVU_PACKAGE_ID or PINAIVU_VAULT_ID not configured" });
    }

    const { request_id, payee_sui_address, amount_nanox, receipt_b64 } = parsed.data;

    try {
        const tx = new Transaction();
        const receiptBytes = Buffer.from(receipt_b64, "base64");

        tx.moveCall({
            target: `${PINAIVU_PACKAGE_ID}::vault::settle`,
            typeArguments: ["0x2::sui::SUI"],
            arguments: [
                tx.object(PINAIVU_VAULT_ID),
                tx.object(PINAIVU_ENCLAVE_CONFIG_ID),
                tx.pure.vector("u8", Array.from(Buffer.from(request_id))),
                tx.pure.address(payee_sui_address),
                tx.pure.u64(amount_nanox),
                tx.pure.vector("u8", Array.from(receiptBytes)),
            ],
        });

        const result = await suiClient.signAndExecuteTransaction({
            signer: operatorKeypair,
            transaction: tx,
            options: { showEffects: true },
        });

        const status = (result.effects as any)?.status?.status ?? "unknown";
        console.log(`[sidecar] settle tx=${result.digest} status=${status} payee=${payee_sui_address} amount=${amount_nanox}`);

        if (status !== "success") {
            const err = (result.effects as any)?.status?.error ?? "tx failed";
            return res.status(500).json({ error: err, tx_digest: result.digest });
        }

        return res.json({ tx_digest: result.digest });
    } catch (err: any) {
        console.error("[sidecar] settle error:", err);
        return res.status(500).json({ error: err.message ?? String(err) });
    }
});

app.listen(PORT, "127.0.0.1", () => {
    console.log(`[sidecar] listening on 127.0.0.1:${PORT} (network=${NETWORK})`);
});
